# Generated by Django 3.1.4 on 2020-12-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_remove_episode_saison'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='numero',
            field=models.AutoField(help_text="Numéro absolu de l'épisode.", primary_key=True, serialize=False),
        ),
    ]
